### ISSUE TITLE
Collision data record

### ISSUE THREAD

**Issue by katilp** [katilp/data-curation#2]
Get familiar with the metadata content of a typical collision dataset

- [x] how it is displayed on the portal e.g. http://opendata.cern.ch/record/6046
- [x] how the json structure looks like http://opendata.cern.ch/record/6046/export/json
- [x] where the source resides https://github.com/cernopendata/opendata.cern.ch/tree/master/cernopendata/modules/fixtures/data/records
- [x] write down questions and add them as a card or an issue here

**Comment by mokotus** [comment]
I have trouble seeing what the github sources are for. What is the connection between that and the webpage on opendata.cern.ch?

**Comment by katilp** [comment]
The github source e.g. https://github.com/cernopendata/opendata.cern.ch/blob/master/cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2012C.json is where the json source for the records reside and the record shows the information which is there. They are typically generated by a script, which we will see later.
In principle, the ..../export/json displays the json content as well, but the source itself is in *.json files in /modules/fixtures/data/records directory.

**Comment by katilp** [comment]
That is: 
- all that appears as a `record` (e.g. http://opendata.cern.ch/record/6046) on the portal has its contents defined in https://github.com/cernopendata/opendata.cern.ch/tree/master/cernopendata/modules/fixtures/data/records  (json files)
- all documentation (typically in md) on the portal (`docs` in e.g. inhttp://opendata.cern.ch/docs/cms-guide-for-condition-database) is in https://github.com/cernopendata/opendata.cern.ch/tree/master/cernopendata/modules/fixtures/data/docs

**Comment by mokotus** [comment]
Okay, i think i get the basic idea. And I'm sure I will understand it more clearly once I learn about the scripts related to these.
