### ISSUE TITLE
configuration file db

### ISSUE THREAD

**Issue by katilp** [katilp/data-curation#5]
Have a look at the database where the data-taking configurations are stored https://cmsweb.cern.ch/confdb/ and search for an example file, e.g. `/cdaq/physics/Run2012/7e33/v4.2/HLT/V1` (not very intuitive, don't waste time with it)

Download the example configuration file (`Export` button in the page top menu, can be done while the GUI say it's loading).

**Comment by mokotus** [comment]
Done
